"use client";

import Sidebar from "@/components/Sidebar";
import { ChakraProvider } from "@chakra-ui/react";
import "./globals.css";

export const metadata = {
    title: "Kwaderno",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <ChakraProvider>
                    <div className="App">
                        <Sidebar />
                        {children}
                    </div>
                </ChakraProvider>
            </body>
        </html>
    );
}
